# 🐳 Simple Docker Setup for Seyyone Website (Next.js only)
# Apache2 runs on host with Let's Encrypt

version: '3.8'

services:
  # Next.js Application
  nextjs-app:
    build: .
    container_name: seyyone-nextjs
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "127.0.0.1:3000:3000"  # Bind to localhost only
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3